## Basic Configuration

baseurl = "https://danzumwalt.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "../gh-pages"

author = "Dan Zumwalt"
title = "Dan Zumwalt"

theme = "goa"

## Site Settings
[params]
author = "Dan Zumwalt"
intro = " "
description = " "
authorimage = "dan.jpg"
dateformat = "Sep 1, 2019"

## Site Meta Settings
[params.meta]
description = "Dan Zumwalt"
keywords = "dan,zumwalt,dan zumwalt,zumwald"
enableRobotsTXT = true

## Social Accounts
[params.social]
github = "zumwald"
linkedin = "dzumwalt"
email = "contact@danzumwalt.com"

## Extras
[params.extra]
poweredby = false
socialmarkup = false

## Main Menu
[[menu.main]]
    name = "resume"
    weight = 100
    identifier = "resume"
    url = "/resume/resume.pdf"